services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_poc
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    extra_hosts:
          - "host.docker.internal:host-gateway" # penting untuk  dapat target di linux
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_poc
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
